// default package
// Generated 2016-01-20 20:45:55 by Hibernate Tools 4.0.0
package pl.edu.pwr.krk.models.entities;

/**
 * Kekpek generated by hbm2java
 */
public class Kekpek implements java.io.Serializable {

	private Integer id;
	private Przedmiotowyefektksztalcenia przedmiotowyefektksztalcenia;
	private Kierunkowyefektksztalcenia kierunkowyefektksztalcenia;

	public Kekpek() {
	}

	public Kekpek(Przedmiotowyefektksztalcenia przedmiotowyefektksztalcenia,
			Kierunkowyefektksztalcenia kierunkowyefektksztalcenia) {
		this.przedmiotowyefektksztalcenia = przedmiotowyefektksztalcenia;
		this.kierunkowyefektksztalcenia = kierunkowyefektksztalcenia;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Przedmiotowyefektksztalcenia getPrzedmiotowyefektksztalcenia() {
		return this.przedmiotowyefektksztalcenia;
	}

	public void setPrzedmiotowyefektksztalcenia(Przedmiotowyefektksztalcenia przedmiotowyefektksztalcenia) {
		this.przedmiotowyefektksztalcenia = przedmiotowyefektksztalcenia;
	}

	public Kierunkowyefektksztalcenia getKierunkowyefektksztalcenia() {
		return this.kierunkowyefektksztalcenia;
	}

	public void setKierunkowyefektksztalcenia(Kierunkowyefektksztalcenia kierunkowyefektksztalcenia) {
		this.kierunkowyefektksztalcenia = kierunkowyefektksztalcenia;
	}

}
