// default package
// Generated 2016-01-20 20:45:55 by Hibernate Tools 4.0.0
package pl.edu.pwr.krk.models.entities;

/**
 * Pekcelprzedmiotu generated by hbm2java
 */
public class Pekcelprzedmiotu implements java.io.Serializable {

	private Integer id;
	private Przedmiotowyefektksztalcenia przedmiotowyefektksztalcenia;
	private Celprzedmiotu celprzedmiotu;

	public Pekcelprzedmiotu() {
	}

	public Pekcelprzedmiotu(Przedmiotowyefektksztalcenia przedmiotowyefektksztalcenia, Celprzedmiotu celprzedmiotu) {
		this.przedmiotowyefektksztalcenia = przedmiotowyefektksztalcenia;
		this.celprzedmiotu = celprzedmiotu;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Przedmiotowyefektksztalcenia getPrzedmiotowyefektksztalcenia() {
		return this.przedmiotowyefektksztalcenia;
	}

	public void setPrzedmiotowyefektksztalcenia(Przedmiotowyefektksztalcenia przedmiotowyefektksztalcenia) {
		this.przedmiotowyefektksztalcenia = przedmiotowyefektksztalcenia;
	}

	public Celprzedmiotu getCelprzedmiotu() {
		return this.celprzedmiotu;
	}

	public void setCelprzedmiotu(Celprzedmiotu celprzedmiotu) {
		this.celprzedmiotu = celprzedmiotu;
	}

}
