// default package
// Generated 2016-01-20 20:45:55 by Hibernate Tools 4.0.0
package pl.edu.pwr.krk.models.entities;

/**
 * Pekocenaosiagnieciapek generated by hbm2java
 */
public class Pekocenaosiagnieciapek implements java.io.Serializable {

	private Integer id;
	private Przedmiotowyefektksztalcenia przedmiotowyefektksztalcenia;
	private Ocenaosiagieciapek ocenaosiagieciapek;

	public Pekocenaosiagnieciapek() {
	}

	public Pekocenaosiagnieciapek(Przedmiotowyefektksztalcenia przedmiotowyefektksztalcenia,
			Ocenaosiagieciapek ocenaosiagieciapek) {
		this.przedmiotowyefektksztalcenia = przedmiotowyefektksztalcenia;
		this.ocenaosiagieciapek = ocenaosiagieciapek;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Przedmiotowyefektksztalcenia getPrzedmiotowyefektksztalcenia() {
		return this.przedmiotowyefektksztalcenia;
	}

	public void setPrzedmiotowyefektksztalcenia(Przedmiotowyefektksztalcenia przedmiotowyefektksztalcenia) {
		this.przedmiotowyefektksztalcenia = przedmiotowyefektksztalcenia;
	}

	public Ocenaosiagieciapek getOcenaosiagieciapek() {
		return this.ocenaosiagieciapek;
	}

	public void setOcenaosiagieciapek(Ocenaosiagieciapek ocenaosiagieciapek) {
		this.ocenaosiagieciapek = ocenaosiagieciapek;
	}

}
