// default package
// Generated 2016-01-17 19:43:59 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

/**
 * Celprzedmiotu generated by hbm2java
 */
public class Celprzedmiotu implements java.io.Serializable {

	private int id;
	private Kartaprzedmiotu kartaprzedmiotu;
	private String numer;
	private String opis;
	private Set<Przedmiotowyefektksztalcenia> przedmiotowyefektksztalcenias = new HashSet<Przedmiotowyefektksztalcenia>(
			0);

	public Celprzedmiotu() {
	}

	public Celprzedmiotu(int id, Kartaprzedmiotu kartaprzedmiotu) {
		this.id = id;
		this.kartaprzedmiotu = kartaprzedmiotu;
	}

	public Celprzedmiotu(int id, Kartaprzedmiotu kartaprzedmiotu, String numer, String opis,
			Set<Przedmiotowyefektksztalcenia> przedmiotowyefektksztalcenias) {
		this.id = id;
		this.kartaprzedmiotu = kartaprzedmiotu;
		this.numer = numer;
		this.opis = opis;
		this.przedmiotowyefektksztalcenias = przedmiotowyefektksztalcenias;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public Kartaprzedmiotu getKartaprzedmiotu() {
		return this.kartaprzedmiotu;
	}

	public void setKartaprzedmiotu(Kartaprzedmiotu kartaprzedmiotu) {
		this.kartaprzedmiotu = kartaprzedmiotu;
	}

	public String getNumer() {
		return this.numer;
	}

	public void setNumer(String numer) {
		this.numer = numer;
	}

	public String getOpis() {
		return this.opis;
	}

	public void setOpis(String opis) {
		this.opis = opis;
	}

	public Set<Przedmiotowyefektksztalcenia> getPrzedmiotowyefektksztalcenias() {
		return this.przedmiotowyefektksztalcenias;
	}

	public void setPrzedmiotowyefektksztalcenias(Set<Przedmiotowyefektksztalcenia> przedmiotowyefektksztalcenias) {
		this.przedmiotowyefektksztalcenias = przedmiotowyefektksztalcenias;
	}

}
