// default package
// Generated 2016-01-17 19:43:59 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

/**
 * Grupakursow generated by hbm2java
 */
public class Grupakursow implements java.io.Serializable {

	private Integer id;
	private Przedmiot przedmiot;
	private String kod;
	private Set<Kurs> kurses = new HashSet<Kurs>(0);

	public Grupakursow() {
	}

	public Grupakursow(Przedmiot przedmiot) {
		this.przedmiot = przedmiot;
	}

	public Grupakursow(Przedmiot przedmiot, String kod, Set<Kurs> kurses) {
		this.przedmiot = przedmiot;
		this.kod = kod;
		this.kurses = kurses;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Przedmiot getPrzedmiot() {
		return this.przedmiot;
	}

	public void setPrzedmiot(Przedmiot przedmiot) {
		this.przedmiot = przedmiot;
	}

	public String getKod() {
		return this.kod;
	}

	public void setKod(String kod) {
		this.kod = kod;
	}

	public Set<Kurs> getKurses() {
		return this.kurses;
	}

	public void setKurses(Set<Kurs> kurses) {
		this.kurses = kurses;
	}

}
