// default package
// Generated 2016-01-17 19:43:59 by Hibernate Tools 4.0.0

/**
 * KekpekId generated by hbm2java
 */
public class KekpekId implements java.io.Serializable {

	private int kierunkowyEfektKsztalceniaid;
	private int przedmiotowyEfektKsztalceniaid;
	private int kierunkowyEfektKsztalceniaSpecjalizacjaid;

	public KekpekId() {
	}

	public KekpekId(int kierunkowyEfektKsztalceniaid, int przedmiotowyEfektKsztalceniaid,
			int kierunkowyEfektKsztalceniaSpecjalizacjaid) {
		this.kierunkowyEfektKsztalceniaid = kierunkowyEfektKsztalceniaid;
		this.przedmiotowyEfektKsztalceniaid = przedmiotowyEfektKsztalceniaid;
		this.kierunkowyEfektKsztalceniaSpecjalizacjaid = kierunkowyEfektKsztalceniaSpecjalizacjaid;
	}

	public int getKierunkowyEfektKsztalceniaid() {
		return this.kierunkowyEfektKsztalceniaid;
	}

	public void setKierunkowyEfektKsztalceniaid(int kierunkowyEfektKsztalceniaid) {
		this.kierunkowyEfektKsztalceniaid = kierunkowyEfektKsztalceniaid;
	}

	public int getPrzedmiotowyEfektKsztalceniaid() {
		return this.przedmiotowyEfektKsztalceniaid;
	}

	public void setPrzedmiotowyEfektKsztalceniaid(int przedmiotowyEfektKsztalceniaid) {
		this.przedmiotowyEfektKsztalceniaid = przedmiotowyEfektKsztalceniaid;
	}

	public int getKierunkowyEfektKsztalceniaSpecjalizacjaid() {
		return this.kierunkowyEfektKsztalceniaSpecjalizacjaid;
	}

	public void setKierunkowyEfektKsztalceniaSpecjalizacjaid(int kierunkowyEfektKsztalceniaSpecjalizacjaid) {
		this.kierunkowyEfektKsztalceniaSpecjalizacjaid = kierunkowyEfektKsztalceniaSpecjalizacjaid;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof KekpekId))
			return false;
		KekpekId castOther = (KekpekId) other;

		return (this.getKierunkowyEfektKsztalceniaid() == castOther.getKierunkowyEfektKsztalceniaid())
				&& (this.getPrzedmiotowyEfektKsztalceniaid() == castOther.getPrzedmiotowyEfektKsztalceniaid())
				&& (this.getKierunkowyEfektKsztalceniaSpecjalizacjaid() == castOther
						.getKierunkowyEfektKsztalceniaSpecjalizacjaid());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getKierunkowyEfektKsztalceniaid();
		result = 37 * result + this.getPrzedmiotowyEfektKsztalceniaid();
		result = 37 * result + this.getKierunkowyEfektKsztalceniaSpecjalizacjaid();
		return result;
	}

}
