// default package
// Generated 2016-01-17 19:43:59 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

/**
 * Kierunekstudiow generated by hbm2java
 */
public class Kierunekstudiow implements java.io.Serializable {

	private int id;
	private Wydzial wydzial;
	private String nazwa;
	private Set<Programksztalcenia> programksztalcenias = new HashSet<Programksztalcenia>(0);
	private Set<Kierunkowyefektksztalcenia> kierunkowyefektksztalcenias = new HashSet<Kierunkowyefektksztalcenia>(0);
	private Set<Specjalizacja> specjalizacjas = new HashSet<Specjalizacja>(0);

	public Kierunekstudiow() {
	}

	public Kierunekstudiow(int id, Wydzial wydzial) {
		this.id = id;
		this.wydzial = wydzial;
	}

	public Kierunekstudiow(int id, Wydzial wydzial, String nazwa, Set<Programksztalcenia> programksztalcenias,
			Set<Kierunkowyefektksztalcenia> kierunkowyefektksztalcenias, Set<Specjalizacja> specjalizacjas) {
		this.id = id;
		this.wydzial = wydzial;
		this.nazwa = nazwa;
		this.programksztalcenias = programksztalcenias;
		this.kierunkowyefektksztalcenias = kierunkowyefektksztalcenias;
		this.specjalizacjas = specjalizacjas;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public Wydzial getWydzial() {
		return this.wydzial;
	}

	public void setWydzial(Wydzial wydzial) {
		this.wydzial = wydzial;
	}

	public String getNazwa() {
		return this.nazwa;
	}

	public void setNazwa(String nazwa) {
		this.nazwa = nazwa;
	}

	public Set<Programksztalcenia> getProgramksztalcenias() {
		return this.programksztalcenias;
	}

	public void setProgramksztalcenias(Set<Programksztalcenia> programksztalcenias) {
		this.programksztalcenias = programksztalcenias;
	}

	public Set<Kierunkowyefektksztalcenia> getKierunkowyefektksztalcenias() {
		return this.kierunkowyefektksztalcenias;
	}

	public void setKierunkowyefektksztalcenias(Set<Kierunkowyefektksztalcenia> kierunkowyefektksztalcenias) {
		this.kierunkowyefektksztalcenias = kierunkowyefektksztalcenias;
	}

	public Set<Specjalizacja> getSpecjalizacjas() {
		return this.specjalizacjas;
	}

	public void setSpecjalizacjas(Set<Specjalizacja> specjalizacjas) {
		this.specjalizacjas = specjalizacjas;
	}

}
