// default package
// Generated 2016-01-17 19:43:59 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

/**
 * Kurs generated by hbm2java
 */
public class Kurs implements java.io.Serializable {

	private Integer id;
	private Grupakursow grupakursow;
	private Semestr semestr;
	private Przedmiot przedmiot;
	private String formaZajec;
	private Short ects;
	private Short zzu;
	private Short cnps;
	private String formaZaliczenia;
	private Double punktyP;
	private Double punktyBk;
	private String kod;
	private Short liczbaZajec;
	private Set<Narzedziedydaktyczne> narzedziedydaktycznes = new HashSet<Narzedziedydaktyczne>(0);

	public Kurs() {
	}

	public Kurs(Semestr semestr, Przedmiot przedmiot) {
		this.semestr = semestr;
		this.przedmiot = przedmiot;
	}

	public Kurs(Grupakursow grupakursow, Semestr semestr, Przedmiot przedmiot, String formaZajec, Short ects, Short zzu,
			Short cnps, String formaZaliczenia, Double punktyP, Double punktyBk, String kod, Short liczbaZajec,
			Set<Narzedziedydaktyczne> narzedziedydaktycznes) {
		this.grupakursow = grupakursow;
		this.semestr = semestr;
		this.przedmiot = przedmiot;
		this.formaZajec = formaZajec;
		this.ects = ects;
		this.zzu = zzu;
		this.cnps = cnps;
		this.formaZaliczenia = formaZaliczenia;
		this.punktyP = punktyP;
		this.punktyBk = punktyBk;
		this.kod = kod;
		this.liczbaZajec = liczbaZajec;
		this.narzedziedydaktycznes = narzedziedydaktycznes;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Grupakursow getGrupakursow() {
		return this.grupakursow;
	}

	public void setGrupakursow(Grupakursow grupakursow) {
		this.grupakursow = grupakursow;
	}

	public Semestr getSemestr() {
		return this.semestr;
	}

	public void setSemestr(Semestr semestr) {
		this.semestr = semestr;
	}

	public Przedmiot getPrzedmiot() {
		return this.przedmiot;
	}

	public void setPrzedmiot(Przedmiot przedmiot) {
		this.przedmiot = przedmiot;
	}

	public String getFormaZajec() {
		return this.formaZajec;
	}

	public void setFormaZajec(String formaZajec) {
		this.formaZajec = formaZajec;
	}

	public Short getEcts() {
		return this.ects;
	}

	public void setEcts(Short ects) {
		this.ects = ects;
	}

	public Short getZzu() {
		return this.zzu;
	}

	public void setZzu(Short zzu) {
		this.zzu = zzu;
	}

	public Short getCnps() {
		return this.cnps;
	}

	public void setCnps(Short cnps) {
		this.cnps = cnps;
	}

	public String getFormaZaliczenia() {
		return this.formaZaliczenia;
	}

	public void setFormaZaliczenia(String formaZaliczenia) {
		this.formaZaliczenia = formaZaliczenia;
	}

	public Double getPunktyP() {
		return this.punktyP;
	}

	public void setPunktyP(Double punktyP) {
		this.punktyP = punktyP;
	}

	public Double getPunktyBk() {
		return this.punktyBk;
	}

	public void setPunktyBk(Double punktyBk) {
		this.punktyBk = punktyBk;
	}

	public String getKod() {
		return this.kod;
	}

	public void setKod(String kod) {
		this.kod = kod;
	}

	public Short getLiczbaZajec() {
		return this.liczbaZajec;
	}

	public void setLiczbaZajec(Short liczbaZajec) {
		this.liczbaZajec = liczbaZajec;
	}

	public Set<Narzedziedydaktyczne> getNarzedziedydaktycznes() {
		return this.narzedziedydaktycznes;
	}

	public void setNarzedziedydaktycznes(Set<Narzedziedydaktyczne> narzedziedydaktycznes) {
		this.narzedziedydaktycznes = narzedziedydaktycznes;
	}

}
