// default package
// Generated 2016-01-17 19:43:59 by Hibernate Tools 4.0.0

/**
 * Mekkek generated by hbm2java
 */
public class Mekkek implements java.io.Serializable {

	private MekkekId id;
	private Kierunkowyefektksztalcenia kierunkowyefektksztalcenia;
	private Ministerialnyefektksztalcenia ministerialnyefektksztalcenia;

	public Mekkek() {
	}

	public Mekkek(MekkekId id, Kierunkowyefektksztalcenia kierunkowyefektksztalcenia,
			Ministerialnyefektksztalcenia ministerialnyefektksztalcenia) {
		this.id = id;
		this.kierunkowyefektksztalcenia = kierunkowyefektksztalcenia;
		this.ministerialnyefektksztalcenia = ministerialnyefektksztalcenia;
	}

	public MekkekId getId() {
		return this.id;
	}

	public void setId(MekkekId id) {
		this.id = id;
	}

	public Kierunkowyefektksztalcenia getKierunkowyefektksztalcenia() {
		return this.kierunkowyefektksztalcenia;
	}

	public void setKierunkowyefektksztalcenia(Kierunkowyefektksztalcenia kierunkowyefektksztalcenia) {
		this.kierunkowyefektksztalcenia = kierunkowyefektksztalcenia;
	}

	public Ministerialnyefektksztalcenia getMinisterialnyefektksztalcenia() {
		return this.ministerialnyefektksztalcenia;
	}

	public void setMinisterialnyefektksztalcenia(Ministerialnyefektksztalcenia ministerialnyefektksztalcenia) {
		this.ministerialnyefektksztalcenia = ministerialnyefektksztalcenia;
	}

}
