// default package
// Generated 2016-01-17 19:43:59 by Hibernate Tools 4.0.0

/**
 * MekkekId generated by hbm2java
 */
public class MekkekId implements java.io.Serializable {

	private int kierunkowyEfektKsztalceniaid;
	private int ministerialnyEfektKsztalceniaid;
	private int kierunkowyEfektKsztalceniaSpecjalizacjaid;

	public MekkekId() {
	}

	public MekkekId(int kierunkowyEfektKsztalceniaid, int ministerialnyEfektKsztalceniaid,
			int kierunkowyEfektKsztalceniaSpecjalizacjaid) {
		this.kierunkowyEfektKsztalceniaid = kierunkowyEfektKsztalceniaid;
		this.ministerialnyEfektKsztalceniaid = ministerialnyEfektKsztalceniaid;
		this.kierunkowyEfektKsztalceniaSpecjalizacjaid = kierunkowyEfektKsztalceniaSpecjalizacjaid;
	}

	public int getKierunkowyEfektKsztalceniaid() {
		return this.kierunkowyEfektKsztalceniaid;
	}

	public void setKierunkowyEfektKsztalceniaid(int kierunkowyEfektKsztalceniaid) {
		this.kierunkowyEfektKsztalceniaid = kierunkowyEfektKsztalceniaid;
	}

	public int getMinisterialnyEfektKsztalceniaid() {
		return this.ministerialnyEfektKsztalceniaid;
	}

	public void setMinisterialnyEfektKsztalceniaid(int ministerialnyEfektKsztalceniaid) {
		this.ministerialnyEfektKsztalceniaid = ministerialnyEfektKsztalceniaid;
	}

	public int getKierunkowyEfektKsztalceniaSpecjalizacjaid() {
		return this.kierunkowyEfektKsztalceniaSpecjalizacjaid;
	}

	public void setKierunkowyEfektKsztalceniaSpecjalizacjaid(int kierunkowyEfektKsztalceniaSpecjalizacjaid) {
		this.kierunkowyEfektKsztalceniaSpecjalizacjaid = kierunkowyEfektKsztalceniaSpecjalizacjaid;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof MekkekId))
			return false;
		MekkekId castOther = (MekkekId) other;

		return (this.getKierunkowyEfektKsztalceniaid() == castOther.getKierunkowyEfektKsztalceniaid())
				&& (this.getMinisterialnyEfektKsztalceniaid() == castOther.getMinisterialnyEfektKsztalceniaid())
				&& (this.getKierunkowyEfektKsztalceniaSpecjalizacjaid() == castOther
						.getKierunkowyEfektKsztalceniaSpecjalizacjaid());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getKierunkowyEfektKsztalceniaid();
		result = 37 * result + this.getMinisterialnyEfektKsztalceniaid();
		result = 37 * result + this.getKierunkowyEfektKsztalceniaSpecjalizacjaid();
		return result;
	}

}
