// default package
// Generated 2016-01-17 19:43:59 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

/**
 * Narzedziedydaktyczne generated by hbm2java
 */
public class Narzedziedydaktyczne implements java.io.Serializable {

	private Integer id;
	private Kartaprzedmiotu kartaprzedmiotu;
	private Kurs kurs;
	private String numer;
	private String opis;
	private Set<Przedmiotowyefektksztalcenia> przedmiotowyefektksztalcenias = new HashSet<Przedmiotowyefektksztalcenia>(
			0);

	public Narzedziedydaktyczne() {
	}

	public Narzedziedydaktyczne(Kartaprzedmiotu kartaprzedmiotu, Kurs kurs) {
		this.kartaprzedmiotu = kartaprzedmiotu;
		this.kurs = kurs;
	}

	public Narzedziedydaktyczne(Kartaprzedmiotu kartaprzedmiotu, Kurs kurs, String numer, String opis,
			Set<Przedmiotowyefektksztalcenia> przedmiotowyefektksztalcenias) {
		this.kartaprzedmiotu = kartaprzedmiotu;
		this.kurs = kurs;
		this.numer = numer;
		this.opis = opis;
		this.przedmiotowyefektksztalcenias = przedmiotowyefektksztalcenias;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Kartaprzedmiotu getKartaprzedmiotu() {
		return this.kartaprzedmiotu;
	}

	public void setKartaprzedmiotu(Kartaprzedmiotu kartaprzedmiotu) {
		this.kartaprzedmiotu = kartaprzedmiotu;
	}

	public Kurs getKurs() {
		return this.kurs;
	}

	public void setKurs(Kurs kurs) {
		this.kurs = kurs;
	}

	public String getNumer() {
		return this.numer;
	}

	public void setNumer(String numer) {
		this.numer = numer;
	}

	public String getOpis() {
		return this.opis;
	}

	public void setOpis(String opis) {
		this.opis = opis;
	}

	public Set<Przedmiotowyefektksztalcenia> getPrzedmiotowyefektksztalcenias() {
		return this.przedmiotowyefektksztalcenias;
	}

	public void setPrzedmiotowyefektksztalcenias(Set<Przedmiotowyefektksztalcenia> przedmiotowyefektksztalcenias) {
		this.przedmiotowyefektksztalcenias = przedmiotowyefektksztalcenias;
	}

}
