// default package
// Generated 2016-01-17 19:43:59 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

/**
 * Obszarksztalcenia generated by hbm2java
 */
public class Obszarksztalcenia implements java.io.Serializable {

	private Integer id;
	private Set<Programksztalcenia> programksztalcenias = new HashSet<Programksztalcenia>(0);
	private Set<Ministerialnyefektksztalcenia> ministerialnyefektksztalcenias = new HashSet<Ministerialnyefektksztalcenia>(
			0);

	public Obszarksztalcenia() {
	}

	public Obszarksztalcenia(Set<Programksztalcenia> programksztalcenias,
			Set<Ministerialnyefektksztalcenia> ministerialnyefektksztalcenias) {
		this.programksztalcenias = programksztalcenias;
		this.ministerialnyefektksztalcenias = ministerialnyefektksztalcenias;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Set<Programksztalcenia> getProgramksztalcenias() {
		return this.programksztalcenias;
	}

	public void setProgramksztalcenias(Set<Programksztalcenia> programksztalcenias) {
		this.programksztalcenias = programksztalcenias;
	}

	public Set<Ministerialnyefektksztalcenia> getMinisterialnyefektksztalcenias() {
		return this.ministerialnyefektksztalcenias;
	}

	public void setMinisterialnyefektksztalcenias(Set<Ministerialnyefektksztalcenia> ministerialnyefektksztalcenias) {
		this.ministerialnyefektksztalcenias = ministerialnyefektksztalcenias;
	}

}
