// default package
// Generated 2016-01-17 19:43:59 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

/**
 * Ocenaosiagieciapek generated by hbm2java
 */
public class Ocenaosiagieciapek implements java.io.Serializable {

	private Integer id;
	private Kartaprzedmiotu kartaprzedmiotu;
	private String rodzajOceny;
	private String numer;
	private String opis;
	private String sposobOceny;
	private Integer column;
	private Set<Przedmiotowyefektksztalcenia> przedmiotowyefektksztalcenias = new HashSet<Przedmiotowyefektksztalcenia>(
			0);

	public Ocenaosiagieciapek() {
	}

	public Ocenaosiagieciapek(Kartaprzedmiotu kartaprzedmiotu, String rodzajOceny) {
		this.kartaprzedmiotu = kartaprzedmiotu;
		this.rodzajOceny = rodzajOceny;
	}

	public Ocenaosiagieciapek(Kartaprzedmiotu kartaprzedmiotu, String rodzajOceny, String numer, String opis,
			String sposobOceny, Integer column, Set<Przedmiotowyefektksztalcenia> przedmiotowyefektksztalcenias) {
		this.kartaprzedmiotu = kartaprzedmiotu;
		this.rodzajOceny = rodzajOceny;
		this.numer = numer;
		this.opis = opis;
		this.sposobOceny = sposobOceny;
		this.column = column;
		this.przedmiotowyefektksztalcenias = przedmiotowyefektksztalcenias;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Kartaprzedmiotu getKartaprzedmiotu() {
		return this.kartaprzedmiotu;
	}

	public void setKartaprzedmiotu(Kartaprzedmiotu kartaprzedmiotu) {
		this.kartaprzedmiotu = kartaprzedmiotu;
	}

	public String getRodzajOceny() {
		return this.rodzajOceny;
	}

	public void setRodzajOceny(String rodzajOceny) {
		this.rodzajOceny = rodzajOceny;
	}

	public String getNumer() {
		return this.numer;
	}

	public void setNumer(String numer) {
		this.numer = numer;
	}

	public String getOpis() {
		return this.opis;
	}

	public void setOpis(String opis) {
		this.opis = opis;
	}

	public String getSposobOceny() {
		return this.sposobOceny;
	}

	public void setSposobOceny(String sposobOceny) {
		this.sposobOceny = sposobOceny;
	}

	public Integer getColumn() {
		return this.column;
	}

	public void setColumn(Integer column) {
		this.column = column;
	}

	public Set<Przedmiotowyefektksztalcenia> getPrzedmiotowyefektksztalcenias() {
		return this.przedmiotowyefektksztalcenias;
	}

	public void setPrzedmiotowyefektksztalcenias(Set<Przedmiotowyefektksztalcenia> przedmiotowyefektksztalcenias) {
		this.przedmiotowyefektksztalcenias = przedmiotowyefektksztalcenias;
	}

}
