// default package
// Generated 2016-01-17 19:43:59 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

/**
 * Planstudiow generated by hbm2java
 */
public class Planstudiow implements java.io.Serializable {

	private Integer id;
	private Programksztalcenia programksztalcenia;
	private Set<Semestr> semestrs = new HashSet<Semestr>(0);

	public Planstudiow() {
	}

	public Planstudiow(Programksztalcenia programksztalcenia) {
		this.programksztalcenia = programksztalcenia;
	}

	public Planstudiow(Programksztalcenia programksztalcenia, Set<Semestr> semestrs) {
		this.programksztalcenia = programksztalcenia;
		this.semestrs = semestrs;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Programksztalcenia getProgramksztalcenia() {
		return this.programksztalcenia;
	}

	public void setProgramksztalcenia(Programksztalcenia programksztalcenia) {
		this.programksztalcenia = programksztalcenia;
	}

	public Set<Semestr> getSemestrs() {
		return this.semestrs;
	}

	public void setSemestrs(Set<Semestr> semestrs) {
		this.semestrs = semestrs;
	}

}
