// default package
// Generated 2016-01-17 19:43:59 by Hibernate Tools 4.0.0

/**
 * Pozycjaliteraturowa generated by hbm2java
 */
public class Pozycjaliteraturowa implements java.io.Serializable {

	private Integer id;
	private Kartaprzedmiotu kartaprzedmiotu;
	private Short pozycja;
	private String opis;
	private String rodzaj;

	public Pozycjaliteraturowa() {
	}

	public Pozycjaliteraturowa(Kartaprzedmiotu kartaprzedmiotu) {
		this.kartaprzedmiotu = kartaprzedmiotu;
	}

	public Pozycjaliteraturowa(Kartaprzedmiotu kartaprzedmiotu, Short pozycja, String opis, String rodzaj) {
		this.kartaprzedmiotu = kartaprzedmiotu;
		this.pozycja = pozycja;
		this.opis = opis;
		this.rodzaj = rodzaj;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Kartaprzedmiotu getKartaprzedmiotu() {
		return this.kartaprzedmiotu;
	}

	public void setKartaprzedmiotu(Kartaprzedmiotu kartaprzedmiotu) {
		this.kartaprzedmiotu = kartaprzedmiotu;
	}

	public Short getPozycja() {
		return this.pozycja;
	}

	public void setPozycja(Short pozycja) {
		this.pozycja = pozycja;
	}

	public String getOpis() {
		return this.opis;
	}

	public void setOpis(String opis) {
		this.opis = opis;
	}

	public String getRodzaj() {
		return this.rodzaj;
	}

	public void setRodzaj(String rodzaj) {
		this.rodzaj = rodzaj;
	}

}
