// default package
// Generated 2016-01-17 19:43:59 by Hibernate Tools 4.0.0

/**
 * PrzedmiotkekId generated by hbm2java
 */
public class PrzedmiotkekId implements java.io.Serializable {

	private int kierunkowyEfektKsztalceniaid;
	private int przedmiotid;
	private int kierunkowyEfektKsztalceniaSpecjalizacjaid;

	public PrzedmiotkekId() {
	}

	public PrzedmiotkekId(int kierunkowyEfektKsztalceniaid, int przedmiotid,
			int kierunkowyEfektKsztalceniaSpecjalizacjaid) {
		this.kierunkowyEfektKsztalceniaid = kierunkowyEfektKsztalceniaid;
		this.przedmiotid = przedmiotid;
		this.kierunkowyEfektKsztalceniaSpecjalizacjaid = kierunkowyEfektKsztalceniaSpecjalizacjaid;
	}

	public int getKierunkowyEfektKsztalceniaid() {
		return this.kierunkowyEfektKsztalceniaid;
	}

	public void setKierunkowyEfektKsztalceniaid(int kierunkowyEfektKsztalceniaid) {
		this.kierunkowyEfektKsztalceniaid = kierunkowyEfektKsztalceniaid;
	}

	public int getPrzedmiotid() {
		return this.przedmiotid;
	}

	public void setPrzedmiotid(int przedmiotid) {
		this.przedmiotid = przedmiotid;
	}

	public int getKierunkowyEfektKsztalceniaSpecjalizacjaid() {
		return this.kierunkowyEfektKsztalceniaSpecjalizacjaid;
	}

	public void setKierunkowyEfektKsztalceniaSpecjalizacjaid(int kierunkowyEfektKsztalceniaSpecjalizacjaid) {
		this.kierunkowyEfektKsztalceniaSpecjalizacjaid = kierunkowyEfektKsztalceniaSpecjalizacjaid;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof PrzedmiotkekId))
			return false;
		PrzedmiotkekId castOther = (PrzedmiotkekId) other;

		return (this.getKierunkowyEfektKsztalceniaid() == castOther.getKierunkowyEfektKsztalceniaid())
				&& (this.getPrzedmiotid() == castOther.getPrzedmiotid())
				&& (this.getKierunkowyEfektKsztalceniaSpecjalizacjaid() == castOther
						.getKierunkowyEfektKsztalceniaSpecjalizacjaid());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getKierunkowyEfektKsztalceniaid();
		result = 37 * result + this.getPrzedmiotid();
		result = 37 * result + this.getKierunkowyEfektKsztalceniaSpecjalizacjaid();
		return result;
	}

}
