// default package
// Generated 2016-01-17 19:43:59 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

/**
 * Przedmiotowyefektksztalcenia generated by hbm2java
 */
public class Przedmiotowyefektksztalcenia implements java.io.Serializable {

	private Integer id;
	private Kartaprzedmiotu kartaprzedmiotu;
	private String zakres;
	private String numer;
	private String opis;
	private Set<Kekpek> kekpeks = new HashSet<Kekpek>(0);
	private Set<Narzedziedydaktyczne> narzedziedydaktycznes = new HashSet<Narzedziedydaktyczne>(0);
	private Set<Celprzedmiotu> celprzedmiotus = new HashSet<Celprzedmiotu>(0);
	private Set<Ocenaosiagieciapek> ocenaosiagieciapeks = new HashSet<Ocenaosiagieciapek>(0);
	private Set<Trescprogramowa> trescprogramowas = new HashSet<Trescprogramowa>(0);

	public Przedmiotowyefektksztalcenia() {
	}

	public Przedmiotowyefektksztalcenia(Kartaprzedmiotu kartaprzedmiotu) {
		this.kartaprzedmiotu = kartaprzedmiotu;
	}

	public Przedmiotowyefektksztalcenia(Kartaprzedmiotu kartaprzedmiotu, String zakres, String numer, String opis,
			Set<Kekpek> kekpeks, Set<Narzedziedydaktyczne> narzedziedydaktycznes, Set<Celprzedmiotu> celprzedmiotus,
			Set<Ocenaosiagieciapek> ocenaosiagieciapeks, Set<Trescprogramowa> trescprogramowas) {
		this.kartaprzedmiotu = kartaprzedmiotu;
		this.zakres = zakres;
		this.numer = numer;
		this.opis = opis;
		this.kekpeks = kekpeks;
		this.narzedziedydaktycznes = narzedziedydaktycznes;
		this.celprzedmiotus = celprzedmiotus;
		this.ocenaosiagieciapeks = ocenaosiagieciapeks;
		this.trescprogramowas = trescprogramowas;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Kartaprzedmiotu getKartaprzedmiotu() {
		return this.kartaprzedmiotu;
	}

	public void setKartaprzedmiotu(Kartaprzedmiotu kartaprzedmiotu) {
		this.kartaprzedmiotu = kartaprzedmiotu;
	}

	public String getZakres() {
		return this.zakres;
	}

	public void setZakres(String zakres) {
		this.zakres = zakres;
	}

	public String getNumer() {
		return this.numer;
	}

	public void setNumer(String numer) {
		this.numer = numer;
	}

	public String getOpis() {
		return this.opis;
	}

	public void setOpis(String opis) {
		this.opis = opis;
	}

	public Set<Kekpek> getKekpeks() {
		return this.kekpeks;
	}

	public void setKekpeks(Set<Kekpek> kekpeks) {
		this.kekpeks = kekpeks;
	}

	public Set<Narzedziedydaktyczne> getNarzedziedydaktycznes() {
		return this.narzedziedydaktycznes;
	}

	public void setNarzedziedydaktycznes(Set<Narzedziedydaktyczne> narzedziedydaktycznes) {
		this.narzedziedydaktycznes = narzedziedydaktycznes;
	}

	public Set<Celprzedmiotu> getCelprzedmiotus() {
		return this.celprzedmiotus;
	}

	public void setCelprzedmiotus(Set<Celprzedmiotu> celprzedmiotus) {
		this.celprzedmiotus = celprzedmiotus;
	}

	public Set<Ocenaosiagieciapek> getOcenaosiagieciapeks() {
		return this.ocenaosiagieciapeks;
	}

	public void setOcenaosiagieciapeks(Set<Ocenaosiagieciapek> ocenaosiagieciapeks) {
		this.ocenaosiagieciapeks = ocenaosiagieciapeks;
	}

	public Set<Trescprogramowa> getTrescprogramowas() {
		return this.trescprogramowas;
	}

	public void setTrescprogramowas(Set<Trescprogramowa> trescprogramowas) {
		this.trescprogramowas = trescprogramowas;
	}

}
