// default package
// Generated 2016-01-17 19:43:59 by Hibernate Tools 4.0.0

/**
 * Przedmiotkek generated by hbm2java
 */
public class Przedmiotkek implements java.io.Serializable {

	private PrzedmiotkekId id;
	private Kierunkowyefektksztalcenia kierunkowyefektksztalcenia;
	private Przedmiot przedmiot;

	public Przedmiotkek() {
	}

	public Przedmiotkek(PrzedmiotkekId id, Kierunkowyefektksztalcenia kierunkowyefektksztalcenia, Przedmiot przedmiot) {
		this.id = id;
		this.kierunkowyefektksztalcenia = kierunkowyefektksztalcenia;
		this.przedmiot = przedmiot;
	}

	public PrzedmiotkekId getId() {
		return this.id;
	}

	public void setId(PrzedmiotkekId id) {
		this.id = id;
	}

	public Kierunkowyefektksztalcenia getKierunkowyefektksztalcenia() {
		return this.kierunkowyefektksztalcenia;
	}

	public void setKierunkowyefektksztalcenia(Kierunkowyefektksztalcenia kierunkowyefektksztalcenia) {
		this.kierunkowyefektksztalcenia = kierunkowyefektksztalcenia;
	}

	public Przedmiot getPrzedmiot() {
		return this.przedmiot;
	}

	public void setPrzedmiot(Przedmiot przedmiot) {
		this.przedmiot = przedmiot;
	}

}
