// default package
// Generated 2016-01-17 19:43:59 by Hibernate Tools 4.0.0

import java.util.Date;

/**
 * Raportsyntetyczny generated by hbm2java
 */
public class Raportsyntetyczny implements java.io.Serializable {

	private Integer id;
	private Uzytkownik uzytkownik;
	private Przedmiot przedmiot;
	private Date data;

	public Raportsyntetyczny() {
	}

	public Raportsyntetyczny(Uzytkownik uzytkownik, Przedmiot przedmiot) {
		this.uzytkownik = uzytkownik;
		this.przedmiot = przedmiot;
	}

	public Raportsyntetyczny(Uzytkownik uzytkownik, Przedmiot przedmiot, Date data) {
		this.uzytkownik = uzytkownik;
		this.przedmiot = przedmiot;
		this.data = data;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Uzytkownik getUzytkownik() {
		return this.uzytkownik;
	}

	public void setUzytkownik(Uzytkownik uzytkownik) {
		this.uzytkownik = uzytkownik;
	}

	public Przedmiot getPrzedmiot() {
		return this.przedmiot;
	}

	public void setPrzedmiot(Przedmiot przedmiot) {
		this.przedmiot = przedmiot;
	}

	public Date getData() {
		return this.data;
	}

	public void setData(Date data) {
		this.data = data;
	}

}
