// default package
// Generated 2016-01-17 19:43:59 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

/**
 * Semestr generated by hbm2java
 */
public class Semestr implements java.io.Serializable {

	private Integer id;
	private Short numer;
	private Set<Kurs> kurses = new HashSet<Kurs>(0);
	private Set<Planstudiow> planstudiows = new HashSet<Planstudiow>(0);

	public Semestr() {
	}

	public Semestr(Short numer, Set<Kurs> kurses, Set<Planstudiow> planstudiows) {
		this.numer = numer;
		this.kurses = kurses;
		this.planstudiows = planstudiows;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Short getNumer() {
		return this.numer;
	}

	public void setNumer(Short numer) {
		this.numer = numer;
	}

	public Set<Kurs> getKurses() {
		return this.kurses;
	}

	public void setKurses(Set<Kurs> kurses) {
		this.kurses = kurses;
	}

	public Set<Planstudiow> getPlanstudiows() {
		return this.planstudiows;
	}

	public void setPlanstudiows(Set<Planstudiow> planstudiows) {
		this.planstudiows = planstudiows;
	}

}
