// default package
// Generated 2016-01-17 19:43:59 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

/**
 * Specjalizacja generated by hbm2java
 */
public class Specjalizacja implements java.io.Serializable {

	private Integer id;
	private Kierunekstudiow kierunekstudiow;
	private String nazwa;
	private Set<Kierunkowyefektksztalcenia> kierunkowyefektksztalcenias = new HashSet<Kierunkowyefektksztalcenia>(0);
	private Set<Przedmiot> przedmiots = new HashSet<Przedmiot>(0);

	public Specjalizacja() {
	}

	public Specjalizacja(Kierunekstudiow kierunekstudiow) {
		this.kierunekstudiow = kierunekstudiow;
	}

	public Specjalizacja(Kierunekstudiow kierunekstudiow, String nazwa,
			Set<Kierunkowyefektksztalcenia> kierunkowyefektksztalcenias, Set<Przedmiot> przedmiots) {
		this.kierunekstudiow = kierunekstudiow;
		this.nazwa = nazwa;
		this.kierunkowyefektksztalcenias = kierunkowyefektksztalcenias;
		this.przedmiots = przedmiots;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Kierunekstudiow getKierunekstudiow() {
		return this.kierunekstudiow;
	}

	public void setKierunekstudiow(Kierunekstudiow kierunekstudiow) {
		this.kierunekstudiow = kierunekstudiow;
	}

	public String getNazwa() {
		return this.nazwa;
	}

	public void setNazwa(String nazwa) {
		this.nazwa = nazwa;
	}

	public Set<Kierunkowyefektksztalcenia> getKierunkowyefektksztalcenias() {
		return this.kierunkowyefektksztalcenias;
	}

	public void setKierunkowyefektksztalcenias(Set<Kierunkowyefektksztalcenia> kierunkowyefektksztalcenias) {
		this.kierunkowyefektksztalcenias = kierunkowyefektksztalcenias;
	}

	public Set<Przedmiot> getPrzedmiots() {
		return this.przedmiots;
	}

	public void setPrzedmiots(Set<Przedmiot> przedmiots) {
		this.przedmiots = przedmiots;
	}

}
