// default package
// Generated 2016-01-17 19:43:59 by Hibernate Tools 4.0.0

/**
 * Wymaganiawstepne generated by hbm2java
 */
public class Wymaganiawstepne implements java.io.Serializable {

	private Integer id;
	private Kartaprzedmiotu kartaprzedmiotu;
	private Short pozycja;
	private String wymaganie;

	public Wymaganiawstepne() {
	}

	public Wymaganiawstepne(Kartaprzedmiotu kartaprzedmiotu) {
		this.kartaprzedmiotu = kartaprzedmiotu;
	}

	public Wymaganiawstepne(Kartaprzedmiotu kartaprzedmiotu, Short pozycja, String wymaganie) {
		this.kartaprzedmiotu = kartaprzedmiotu;
		this.pozycja = pozycja;
		this.wymaganie = wymaganie;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Kartaprzedmiotu getKartaprzedmiotu() {
		return this.kartaprzedmiotu;
	}

	public void setKartaprzedmiotu(Kartaprzedmiotu kartaprzedmiotu) {
		this.kartaprzedmiotu = kartaprzedmiotu;
	}

	public Short getPozycja() {
		return this.pozycja;
	}

	public void setPozycja(Short pozycja) {
		this.pozycja = pozycja;
	}

	public String getWymaganie() {
		return this.wymaganie;
	}

	public void setWymaganie(String wymaganie) {
		this.wymaganie = wymaganie;
	}

}
