// default package
// Generated 2016-01-20 20:45:55 by Hibernate Tools 4.0.0
package pl.edu.pwr.krk.data.entities;

/**
 * Pektrescprogramowa generated by hbm2java
 */
public class Pektrescprogramowa implements java.io.Serializable {

	private Integer id;
	private Trescprogramowa trescprogramowa;
	private Przedmiotowyefektksztalcenia przedmiotowyefektksztalcenia;

	public Pektrescprogramowa() {
	}

	public Pektrescprogramowa(Trescprogramowa trescprogramowa,
			Przedmiotowyefektksztalcenia przedmiotowyefektksztalcenia) {
		this.trescprogramowa = trescprogramowa;
		this.przedmiotowyefektksztalcenia = przedmiotowyefektksztalcenia;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Trescprogramowa getTrescprogramowa() {
		return this.trescprogramowa;
	}

	public void setTrescprogramowa(Trescprogramowa trescprogramowa) {
		this.trescprogramowa = trescprogramowa;
	}

	public Przedmiotowyefektksztalcenia getPrzedmiotowyefektksztalcenia() {
		return this.przedmiotowyefektksztalcenia;
	}

	public void setPrzedmiotowyefektksztalcenia(Przedmiotowyefektksztalcenia przedmiotowyefektksztalcenia) {
		this.przedmiotowyefektksztalcenia = przedmiotowyefektksztalcenia;
	}

}
