// default package
// Generated 2016-01-20 20:45:55 by Hibernate Tools 4.0.0
package pl.edu.pwr.krk.data.entities;

import java.util.HashSet;
import java.util.Set;

/**
 * Przedmiot generated by hbm2java
 */
public class Przedmiot implements java.io.Serializable {

	private int id;
	private Specjalizacja specjalizacja;
	private Uzytkownik uzytkownik;
	private Modulksztalcenia modulksztalcenia;
	private String rodzaj;
	private String nazwaPl;
	private String nazwaEn;
	private String kod;
	private int column;
	private Set<Przedmiotkek> przedmiotkeks = new HashSet<Przedmiotkek>(0);
	private Set<Grupakursow> grupakursows = new HashSet<Grupakursow>(0);
	private Set<Raportsyntetyczny> raportsyntetycznies = new HashSet<Raportsyntetyczny>(0);
	private Set<Kartaprzedmiotu> kartaprzedmiotus = new HashSet<Kartaprzedmiotu>(0);
	private Set<Kurs> kurses = new HashSet<Kurs>(0);

	public Przedmiot() {
	}

	public Przedmiot(int id, Uzytkownik uzytkownik, Modulksztalcenia modulksztalcenia, String rodzaj, String nazwaPl,
			String nazwaEn, String kod, int column) {
		this.id = id;
		this.uzytkownik = uzytkownik;
		this.modulksztalcenia = modulksztalcenia;
		this.rodzaj = rodzaj;
		this.nazwaPl = nazwaPl;
		this.nazwaEn = nazwaEn;
		this.kod = kod;
		this.column = column;
	}

	public Przedmiot(int id, Specjalizacja specjalizacja, Uzytkownik uzytkownik, Modulksztalcenia modulksztalcenia,
			String rodzaj, String nazwaPl, String nazwaEn, String kod, int column, Set<Przedmiotkek> przedmiotkeks,
			Set<Grupakursow> grupakursows, Set<Raportsyntetyczny> raportsyntetycznies,
			Set<Kartaprzedmiotu> kartaprzedmiotus, Set<Kurs> kurses) {
		this.id = id;
		this.specjalizacja = specjalizacja;
		this.uzytkownik = uzytkownik;
		this.modulksztalcenia = modulksztalcenia;
		this.rodzaj = rodzaj;
		this.nazwaPl = nazwaPl;
		this.nazwaEn = nazwaEn;
		this.kod = kod;
		this.column = column;
		this.przedmiotkeks = przedmiotkeks;
		this.grupakursows = grupakursows;
		this.raportsyntetycznies = raportsyntetycznies;
		this.kartaprzedmiotus = kartaprzedmiotus;
		this.kurses = kurses;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public Specjalizacja getSpecjalizacja() {
		return this.specjalizacja;
	}

	public void setSpecjalizacja(Specjalizacja specjalizacja) {
		this.specjalizacja = specjalizacja;
	}

	public Uzytkownik getUzytkownik() {
		return this.uzytkownik;
	}

	public void setUzytkownik(Uzytkownik uzytkownik) {
		this.uzytkownik = uzytkownik;
	}

	public Modulksztalcenia getModulksztalcenia() {
		return this.modulksztalcenia;
	}

	public void setModulksztalcenia(Modulksztalcenia modulksztalcenia) {
		this.modulksztalcenia = modulksztalcenia;
	}

	public String getRodzaj() {
		return this.rodzaj;
	}

	public void setRodzaj(String rodzaj) {
		this.rodzaj = rodzaj;
	}

	public String getNazwaPl() {
		return this.nazwaPl;
	}

	public void setNazwaPl(String nazwaPl) {
		this.nazwaPl = nazwaPl;
	}

	public String getNazwaEn() {
		return this.nazwaEn;
	}

	public void setNazwaEn(String nazwaEn) {
		this.nazwaEn = nazwaEn;
	}

	public String getKod() {
		return this.kod;
	}

	public void setKod(String kod) {
		this.kod = kod;
	}

	public int getColumn() {
		return this.column;
	}

	public void setColumn(int column) {
		this.column = column;
	}

	public Set<Przedmiotkek> getPrzedmiotkeks() {
		return this.przedmiotkeks;
	}

	public void setPrzedmiotkeks(Set<Przedmiotkek> przedmiotkeks) {
		this.przedmiotkeks = przedmiotkeks;
	}

	public Set<Grupakursow> getGrupakursows() {
		return this.grupakursows;
	}

	public void setGrupakursows(Set<Grupakursow> grupakursows) {
		this.grupakursows = grupakursows;
	}

	public Set<Raportsyntetyczny> getRaportsyntetycznies() {
		return this.raportsyntetycznies;
	}

	public void setRaportsyntetycznies(Set<Raportsyntetyczny> raportsyntetycznies) {
		this.raportsyntetycznies = raportsyntetycznies;
	}

	public Set<Kartaprzedmiotu> getKartaprzedmiotus() {
		return this.kartaprzedmiotus;
	}

	public void setKartaprzedmiotus(Set<Kartaprzedmiotu> kartaprzedmiotus) {
		this.kartaprzedmiotus = kartaprzedmiotus;
	}

	public Set<Kurs> getKurses() {
		return this.kurses;
	}

	public void setKurses(Set<Kurs> kurses) {
		this.kurses = kurses;
	}

}
